export const WorkflowTriggerEvents = {
  BEFORE_EVENT: "BEFORE_EVENT",
  EVENT_CANCELLED: "EVENT_CANCELLED",
  NEW_EVENT: "NEW_EVENT",
  RESCHEDULE_EVENT: "RESCHEDULE_EVENT",
  AFTER_EVENT: "AFTER_EVENT",
};
